### ISSUE TITLE
[BUG] Tool button duplication 

### ISSUE THREAD

**Issue by HippyCraig** [averrin/alpha-suit#3] opened 2022-10-15 22:01 UTC
**Module Version:** v0.2.2

**Describe the bug**
When I load a scene there are now two alpha items in tool bar they apear to do the same thing.

**To Reproduce**
1. Enable the mod
2. If no map is shown it shows 1 Alpha toolbar icon
3. Load any scene
4. There are now two Apha Toolbar Icons

**Screenshots**
![image](https://user-images.githubusercontent.com/17074456/196009171-a15e9300-222b-4dba-87c3-4faf9a64ae8b.png)

**Browser:**
 - Chrome Latest

**Foundry Version:** 
v10 288

**Game System:** 
5e

**Comment by averrin** [comment] 2022-10-15 22:07
Could you please clarify, what modules with additional buttons do you have? I cannot reproduce it, but modules that also adds their buttons can interfere.

**Comment by HippyCraig** [comment] 2022-10-16 03:10
This might be related to super select module I have been getting some strange behavior from having that enabled

**Comment by averrin** [comment] 2022-10-16 16:35
I hope, it was fixed in the latest release. I still cannot reproduce, but i add some deduplication code. Please reopen if it's still present and add list of your modules (or use "find a culprit" one)

**Closed as completed by averrin** 2022-10-16 16:35 UTC
Labels: bug
